name: survey_simulator
description: Simulator for testing survey conditions.
version: 0.1.0
repository: https://github.com/eliasyishak/survey_simulator

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  file: ^7.0.0
  http: ^1.1.0
  path: ^1.8.3
  unified_analytics: ^5.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  lints: ^3.0.0
  test: ^1.24.0
